class Arrow {
    constructor(x,y){
        this.x=x;
        this.y=y;
        this.rotation=0;
        this.color='#f1f1f1';
    }
    draw(context){
        context.save();
        context.translate(this.x,this.y);
        context.rotate(this.rotation);
        context.lineWidth=5;
        context.fillStyle=this.color;
        context.beginPath();
        context.moveTo(-100,-10);
        context.lineTo(0,-10);
        context.lineTo(0,-40);
        context.lineTo(50,0);
        context.lineTo(0,40);
        context.lineTo(0,10);
        context.lineTo(-100,10);
        context.lineTo(-100,-10);
        context.closePath();
        context.stroke();
        context.fill();
        context.restore();
    }

}
